kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: wso2
reclaimPolicy: Retain
allowVolumeExpansion: true
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
